spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clinic?serverTimezone=CET
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      dll-auto: verify
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  messages:
    basename: messages/messages


